In [1]:
import numpy as np
import matplotlib.pyplot as plt

def read_mesh_coordinates(file_path):
    """Reads mesh cell coordinates from the specified OpenFOAM C file."""
    with open(file_path, 'r') as file:
        lines = file.readlines()

    # Locate the start of the coordinates list
    start_index = None
    for i, line in enumerate(lines):
        if 'nonuniform List<vector>' in line:
            start_index = i + 2  # The data starts two lines after this
            break

    if start_index is None:
        raise ValueError("Start of coordinates data (nonuniform List<vector>) not found in the file.")

    coordinates = []
    for line in lines[start_index:]:
        line = line.strip()
        if line.startswith(')'):  # End of the list
            break
        if line.startswith('(') and line.endswith(')'):
            coord = line.strip('()').split()
            coordinates.append([float(c) for c in coord])

    return np.array(coordinates)

In [2]:
c_file_path = "/home/vhsingh/Geo-UPSplus/Diff_FNO_Experiments/CE-CRP_openfoam/C"
point_coordinates = read_mesh_coordinates(c_file_path)

In [3]:
print(point_coordinates.shape)

(16320, 3)


In [5]:
def transform_coordinates(point_coordinates, hyperparameter):
    """
    Transforms the point coordinates into a 3D array of shape [total_points, 2, hyperparameter].
    
    Args:
        point_coordinates (numpy.ndarray): Array of shape [total_points, 3] with x, y, z coordinates.
        hyperparameter (int): Number of repetitions for each coordinate value.

    Returns:
        numpy.ndarray: Transformed 3D array of shape [total_points, 2, hyperparameter].
    """
    total_points = point_coordinates.shape[0]
    # Extract x and y coordinates
    x_coords = point_coordinates[:, 0]
    y_coords = point_coordinates[:, 1]

    # Repeat each coordinate value 'hyperparameter' times
    x_repeated = np.repeat(x_coords[:, np.newaxis], hyperparameter, axis=1)  # [total_points, hyperparameter]
    y_repeated = np.repeat(y_coords[:, np.newaxis], hyperparameter, axis=1)  # [total_points, hyperparameter]

    # Stack x and y coordinates along a new axis to form a 3D array
    transformed = np.stack((x_repeated, y_repeated), axis=1)  # [total_points, 2, hyperparameter]

    return transformed

In [6]:
# Set the hyperparameter
hyperparameter = 5

# Transform coordinates
transformed_coordinates = transform_coordinates(point_coordinates, hyperparameter)

print("Transformed Coordinates Shape:", transformed_coordinates.shape)
print("Transformed Coordinates Example:\n", transformed_coordinates)

Transformed Coordinates Shape: (16320, 2, 5)
Transformed Coordinates Example:
 [[[0.00390625 0.00390625 0.00390625 0.00390625 0.00390625]
  [0.00390625 0.00390625 0.00390625 0.00390625 0.00390625]]

 [[0.0117188  0.0117188  0.0117188  0.0117188  0.0117188 ]
  [0.00390625 0.00390625 0.00390625 0.00390625 0.00390625]]

 [[0.0195312  0.0195312  0.0195312  0.0195312  0.0195312 ]
  [0.00390625 0.00390625 0.00390625 0.00390625 0.00390625]]

 ...

 [[0.980469   0.980469   0.980469   0.980469   0.980469  ]
  [0.996094   0.996094   0.996094   0.996094   0.996094  ]]

 [[0.988281   0.988281   0.988281   0.988281   0.988281  ]
  [0.996094   0.996094   0.996094   0.996094   0.996094  ]]

 [[0.996094   0.996094   0.996094   0.996094   0.996094  ]
  [0.996094   0.996094   0.996094   0.996094   0.996094  ]]]


In [2]:
import numpy as np
result = np.load("/home/vhsingh/Geo-UPSplus/Diff_FNO_Experiments/CE-CRP_openfoam/CE-RP_Openfoam_Irregular.npy")
print(result.shape)

(1000, 21, 16320, 4)
